name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"   # Trigger the workflow on version tags (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime:
          - osx-x64
          - osx-arm64
          - win-x64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Publish CLI tool for ${{ matrix.runtime }}
        run: dotnet publish src/console/console.csproj -c Release -r ${{ matrix.runtime }} --self-contained true -o ./publish/${{ matrix.runtime }}

      - name: Upload artifact for ${{ matrix.runtime }}
        uses: actions/upload-artifact@v4
        with:
          name: fbl-${{ matrix.runtime }}
          path: ./publish/${{ matrix.runtime }}
